version: '3.10'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["./entrypoint.sh"]
    env_file:
      - .env
    environment:
      - "ENV_FILE_PATH=.env"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
